language: python
python:
  - "3.6"
# command to install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pydocstyle
# command to run tests
script:
  - flake8
  - pydocstyle